name: Auto Build & Version

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ☕ Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🔢 Auto version bump
        run: |
          VERSION=$(grep -m1 "<version>" pom.xml | sed -E 's/.*<version>(.*)<\/version>.*/\1/')
          echo "Current version: $VERSION"

          BASE=$(echo $VERSION | cut -d. -f1-2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$BASE.$NEW_PATCH"

          echo "New version: $NEW_VERSION"

          sed -i "s/$VERSION/$NEW_VERSION/g" pom.xml

      - name: 🛠 Build
        run: mvn clean package

      - name: 📦 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: "**/target/*.jar"
